pipeline {
    agent any

    stages {
        stage('Compile and Clean') {
            steps {
                sh 'mvn clean install'
            }
        }
        stage('Build Docker image'){
            steps {
            }
        }
        stage('Docker Login'){
            steps {
            }
        }
        stage('Docker Push'){
            steps {
                sh 'docker push nhathoang/jenkins_springboot_deploy:lastest'
            }
        }
        stage('Docker deploy'){
            steps {
                sh 'docker run -itd -p  8081:8080 nhathoang/jenkins_springboot_deploy:lastest'
            }
        }
    }

    post {
        success {
          echo "SUCCESSFUL"
        }
        failure {
          echo "FAILED"
        }
      }
}
